
# A string used to distinguish different Supabase projects on the same host. Defaults to the project reference.
project_id = "jrvhqkilzxopesfmpjbz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions]
host = "localhost"
port = 54325

# Function configurations with verify_jwt settings
[functions.request-pharmacy-verification-email]
verify_jwt = false

[functions.create-pharmacy-rls-helpers]
verify_jwt = false

[functions.get-pharmacy-verifications]
verify_jwt = true

[functions.custom-email]
verify_jwt = false
